theme: alembic-jekyll-theme
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - netlify.toml
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
url: ''
baseurl: ''
title: nikydix.com
description: This is my new website
permalink: pretty
logo: 'https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52'
paginate: 5
paginate_path: 'blog/page:num'
navigation_header:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Garden
    url: /garden/
  - title: Donate
    url: /donate/
navigation_footer:
  - title: Back to top
    url: '#top'
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: |
      Welcome to my garden
    feature_image: 'https://picsum.photos/2560/600?image=866'
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: pages
    values:
      layout: page
